[package]
name = "rusqly"
version = "0.1.0"
authors = ["gky360 <gky360@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "2.0.0"
failure = "0.1.5"
lazy_static = "1.3.0"
rustyline = "4.1.0"
structopt = "0.2.15"